### ISSUE TITLE
Build & Test Failure

### ISSUE THREAD

**Issue by honght0068** [Azure/azure-notificationhubs-java-backend#10]
Hi, 

Please advice.

Results :

Failed tests:   InstallationWnsFull(com.windowsazure.messaging.InstallationParse
Test)

Tests run: 24, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.371 s
[INFO] Finished at: 2015-10-12T13:33:07+08:00
[INFO] Final Memory: 7M/16M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
12.4:test (default-test) on project NotificationHubs: There are test failures.
[ERROR]
[ERROR] Please refer to C:\apache-maven-3.3.3\NotificationHubs\target\surefire-r
eports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on proj
ect NotificationHubs: There are test failures.

Please refer to C:\apache-maven-3.3.3\NotificationHubs\target\surefire-reports f
or the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures
.

Please refer to C:\apache-maven-3.3.3\NotificationHubs\target\surefire-reports f
or the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(Suref
ireHelper.java:83)
        at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary(Surefire
Plugin.java:176)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(Surefir
ePlugin.java:150)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPre
conditionsChecked(AbstractSurefireMojo.java:650)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(Abstrac
tSurefireMojo.java:586)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by mpodwysocki** [comment]
Closing as per fix
